### ISSUE TITLE
Inconsistent documentation InformationService

### ISSUE THREAD

**Issue by CEiderEVIDENT** [gematik/epa-deployment#25]
Within the documentation on the main page it is written:
```
Information Service (information-service)
....
Limitations:
.....
 for record status it will always send HTTP code **200** (OK)
``` 

But  information/application.yaml says
```
      nested-responses:
        204:
          response:
            statusCode: **204**
``` 
Running actual Image deployment-1.0.8 repsonses with 204 and not 200
